package com.bumptech.glide;

import android.content.Context;

/**
 * Hand-written replacement for the class normally generated by Glide's annotation processor.
 *
 * <p>Glide's KSP processor (4.16.0) crashes on the {@code okhttp3-integration} indexer
 * ("this and base files have different roots"), and kapt is not available under AGP 9's
 * built-in Kotlin. Glide discovers this exact class by name via reflection from
 * {@code Glide.initializeGlide}, so providing it here restores {@link
 * erl.webdavtoon.MyGlideModule} without any annotation processing.
 */
final class GeneratedAppGlideModuleImpl extends GeneratedAppGlideModule {

    private final erl.webdavtoon.MyGlideModule appGlideModule = new erl.webdavtoon.MyGlideModule();

    GeneratedAppGlideModuleImpl(Context context) {
        super();
    }

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        appGlideModule.applyOptions(context, builder);
    }

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        appGlideModule.registerComponents(context, glide, registry);
    }
}
